import { Injectable } from '@angular/core';
import { Int_Hostels } from '../Interfaces/Int_Hostels';

@Injectable({
  providedIn: 'root',
})
export class srv_Hostels {
  mock_Hostels: Int_Hostels[] = [
    {
      HostelsId: 1,
      HostelsName: 'מלון ציפורי בכנרת',
      RegionId: 2,
      Address: 'הירקון 1, טבריה',
      Description:
        'מלון אירוח מוביל לציבור שומר מצוות, ארוחות ברמה גבוהה ובית כנסת במתחם.',
      NumberOfPlaces: 120,
      kashrutId: 1,
      Phone: '04-6712345',
    },
    {
      HostelsId: 2,
      HostelsName: 'אחוזת נוף צפת',
      RegionId: 1,
      Address: 'חזון איש 4, צפת',
      Description:
        'מתחם וילות וצימרים מרווח למשפחות וקבוצות, קרוב לבתי כנסת ומקואות.',
      NumberOfPlaces: 25,
      kashrutId: 5,
      Phone: '04-6974125',
    },
    {
      HostelsId: 3,
      HostelsName: "מלון ויז'ניץ ציפורי קלאס",
      RegionId: 5,
      Address: 'גבעת פנחס, בני ברק',
      Description:
        'מלון אירוח חסידי מפואר, מתאים במיוחד לשבתות חתן ואירועים משפחתיים.',
      NumberOfPlaces: 150,
      kashrutId: 2,
      Phone: '03-5748596',
    },
    {
      HostelsId: 4,
      HostelsName: 'בית הארחה הרובע היהודי',
      RegionId: 7,
      Address: 'הרובע היהודי, ירושלים',
      Description:
        'אירוח קבוצתי ומשפחתי בלב העיר העתיקה, מרחק הליכה קצר מהכותל המערבי.',
      NumberOfPlaces: 85,
      kashrutId: 3,
      Phone: '02-6285412',
    },
    {
      HostelsId: 5,
      HostelsName: 'קמפוס קוממיות',
      RegionId: 6,
      Address: 'מושב קוממיות',
      Description:
        'מתחם אירוח כפרי שקט באווירה תורנית, מתאים לסמינריונים ושבתות גיבוש.',
      NumberOfPlaces: 200,
      kashrutId: 1,
      Phone: '08-8501234',
    },
    {
      HostelsId: 6,
      HostelsName: 'מלון גלי צאנז',
      RegionId: 5,
      Address: 'חוף צאנז, נתניה',
      Description:
        'מלון מפואר על קו המים סמוך לקריה החסידית, גישה ישירה לחוף הנפרד.',
      NumberOfPlaces: 110,
      kashrutId: 10,
      Phone: '09-8625555',
    },
    {
      HostelsId: 7,
      HostelsName: 'אחוזת מרנס צפת',
      RegionId: 1,
      Address: 'הרובע היהודי, צפת',
      Description:
        'סוויטות מפוארות בסגנון עתיק, מתאים לזוגות ומשפחות המחפשות שקט.',
      NumberOfPlaces: 18,
      kashrutId: 1,
      Phone: '04-6921144',
    },
    {
      HostelsId: 8,
      HostelsName: 'מלון בית טוב ירושלים',
      RegionId: 7,
      Address: 'מלכי ישראל 24, ירושלים',
      Description: 'מלון נעים בלב שכונת גאולה, חוויית אירוח ירושלמית אותנטית.',
      NumberOfPlaces: 45,
      kashrutId: 1,
      Phone: '02-5384411',
    },
    {
      HostelsId: 9,
      HostelsName: 'צימר הבית באור הגנוז',
      RegionId: 1,
      Address: 'יישוב אור הגנוז',
      Description: 'צימרים מרווחים למשפחות ביישוב דתי-קהילתי למרגלות המירון.',
      NumberOfPlaces: 30,
      kashrutId: 5,
      Phone: '04-6987744',
    },
    {
      HostelsId: 10,
      HostelsName: 'פנינת השומרון',
      RegionId: 6,
      Address: 'אלון מורה',
      Description:
        'יחידות אירוח משפחתיות עם נוף פנורמי להרי השומרון, שקט ומבודד.',
      NumberOfPlaces: 20,
      kashrutId: 7,
      Phone: '02-9401122',
    },
    {
      HostelsId: 11,
      HostelsName: 'בית הארחה חפץ חיים',
      RegionId: 6,
      Address: 'קיבוץ חפץ חיים',
      Description: 'אירוח כפרי מהדרין ברמה גבוהה, מדשאות רחבות ומתקנים לילדים.',
      NumberOfPlaces: 250,
      kashrutId: 5,
      Phone: '08-8593111',
    },
    {
      HostelsId: 12,
      HostelsName: 'מלון ארמונות המלך',
      RegionId: 7,
      Address: 'ירמיהו 12, ירושלים',
      Description: 'מלון דירות יוקרתי קרוב למרכזי החסידות והתורה בירושלים.',
      NumberOfPlaces: 70,
      kashrutId: 2,
      Phone: '02-6504488',
    },
    {
      HostelsId: 13,
      HostelsName: 'מתחם הנופש תושיה',
      RegionId: 9,
      Address: 'תושיה',
      Description:
        'צימרים כפריים בדרום הארץ, אווירה רגועה ומתאימה לשומרי מצוות.',
      NumberOfPlaces: 35,
      kashrutId: 7,
      Phone: '08-9941155',
    },
    {
      HostelsId: 14,
      HostelsName: 'מלון לב בני ברק',
      RegionId: 5,
      Address: 'רבי עקיבא 50, בני ברק',
      Description:
        'אירוח עסקי ומשפחתי בלב העיר, גישה נוחה לתחבורה ציבורית וחנויות.',
      NumberOfPlaces: 50,
      kashrutId: 2,
      Phone: '03-6182233',
    },
    {
      HostelsId: 15,
      HostelsName: 'אחוזת הנופש מירון',
      RegionId: 1,
      Address: 'מושב מירון',
      Description:
        'דירות אירוח גדולות במרחק הליכה קצר מציון הרשב"י, מתאים לשבתות.',
      NumberOfPlaces: 60,
      kashrutId: 1,
      Phone: '04-6991122',
    },
    {
      HostelsId: 16,
      HostelsName: 'קמפוס ישיבת נתיבות',
      RegionId: 9,
      Address: 'נתיבות',
      Description:
        'מתחם חדרים לקבוצות וסמינריונים, אולמות לימוד וחדר אוכל גדול.',
      NumberOfPlaces: 180,
      kashrutId: 3,
      Phone: '08-9942233',
    },
    {
      HostelsId: 17,
      HostelsName: 'מלון דירות נופי כנרת',
      RegionId: 2,
      Address: 'קריית שמואל, טבריה',
      Description: 'דירות נופש מאובזרות עם נוף ישיר לכנרת, בלב השכונה הדתית.',
      NumberOfPlaces: 40,
      kashrutId: 1,
      Phone: '04-6725544',
    },
    {
      HostelsId: 18,
      HostelsName: 'אכסניית קדומים',
      RegionId: 6,
      Address: 'קדומים',
      Description: 'אירוח קבוצתי ומשפחתי בשומרון, נוף הררי ואווירה קהילתית.',
      NumberOfPlaces: 90,
      kashrutId: 7,
      Phone: '02-9971166',
    },
    {
      HostelsId: 19,
      HostelsName: 'סוויטות רובין בצפת',
      RegionId: 1,
      Address: 'רחוב האר"י, צפת',
      Description: 'מתחם אירוח יוקרתי ושקט ברובע היהודי, נוף גלילי קסום.',
      NumberOfPlaces: 16,
      kashrutId: 5,
      Phone: '04-6923322',
    },
    {
      HostelsId: 20,
      HostelsName: 'סאטמר נופש ואירוח',
      RegionId: 7,
      Address: 'עזרת תורה, ירושלים',
      Description: 'דירות אירוח רחבות ידיים לשבתות חתן ושמחות משפחתיות.',
      NumberOfPlaces: 75,
      kashrutId: 1,
      Phone: '02-5374455',
    },
    {
      HostelsId: 21,
      HostelsName: 'מלון נווה אילן מהדרין',
      RegionId: 6,
      Address: 'נווה אילן',
      Description:
        'מלון אירוח בהרי יהודה, שטחים ירוקים פתוחים והתאמה מלאה למשפחות.',
      NumberOfPlaces: 160,
      kashrutId: 3,
      Phone: '02-5339999',
    },
    {
      HostelsId: 22,
      HostelsName: 'וילת השלום בחצור',
      RegionId: 1,
      Address: 'חצור הגלילית',
      Description:
        'מתחם וילה יוקרתי עם בריכה מוצנעת ושעות נפרדות, קרוב לקבר חוני המעגל.',
      NumberOfPlaces: 22,
      kashrutId: 5,
      Phone: '04-6931188',
    },
    {
      HostelsId: 23,
      HostelsName: 'בית הארחה עטרת התורה',
      RegionId: 5,
      Address: 'רחוב חזון איש, בני ברק',
      Description:
        'חדרי אירוח נקיים ומסודרים במרכז בני ברק, מיועד בעיקר לזוגות.',
      NumberOfPlaces: 30,
      kashrutId: 2,
      Phone: '03-5701122',
    },
    {
      HostelsId: 24,
      HostelsName: 'אכסניית מעלה עמוס',
      RegionId: 6,
      Address: 'יישוב מעלה עמוס',
      Description: 'מתחם אירוח מבודד ושקט המתאים לקבוצות ישיבות וסמינרים.',
      NumberOfPlaces: 140,
      kashrutId: 4,
      Phone: '02-9938877',
    },
    {
      HostelsId: 25,
      HostelsName: 'צימרים מנחת חינוך',
      RegionId: 2,
      Address: 'מושב תפוח',
      Description: 'צימרים כפריים עם דגש על פרטיות מלאה ואווירה רגועה.',
      NumberOfPlaces: 15,
      kashrutId: 7,
      Phone: '02-9403344',
    },
    {
      HostelsId: 26,
      HostelsName: 'מלון קראון מהדרין ירושלים',
      RegionId: 7,
      Address: 'רחוב הנביאים, ירושלים',
      Description:
        'מלון בוטיק יוקרתי המציע אירוח מוקפד לשומרי מצוות עם אוכל גורמה.',
      NumberOfPlaces: 65,
      kashrutId: 1,
      Phone: '02-6223344',
    },
    {
      HostelsId: 27,
      HostelsName: 'קמפוס נווה הרצוג',
      RegionId: 5,
      Address: 'ניר גלים',
      Description: 'מתחם אירוח רחב ידיים עם מגרשי ספורט מוצנעים ואולמות כנסים.',
      NumberOfPlaces: 300,
      kashrutId: 5,
      Phone: '08-8561122',
    },
    {
      HostelsId: 28,
      HostelsName: 'סוויטות נוף המירון',
      RegionId: 1,
      Address: 'יישוב בר יוחאי',
      Description: 'צימרים מפוארים ומאובזרים למשפחות בלב הגליל העליון.',
      NumberOfPlaces: 28,
      kashrutId: 1,
      Phone: '04-6981155',
    },
    {
      HostelsId: 29,
      HostelsName: 'בית הארחה בית וגן',
      RegionId: 7,
      Address: 'פסגת זאב, ירושלים',
      Description: 'מתחם הארחה שקט לקבוצות ומשפחות, מחירים נוחים ושירות אדיב.',
      NumberOfPlaces: 100,
      kashrutId: 3,
      Phone: '02-5851122',
    },
    {
      HostelsId: 30,
      HostelsName: 'וילות חסדי השם בקוממיות',
      RegionId: 6,
      Address: 'מושב קוממיות',
      Description: 'מתחם וילות יוקרתיות המותאמות במיוחד למשפחות ברוכות ילדים.',
      NumberOfPlaces: 45,
      kashrutId: 1,
      Phone: '08-8502211',
    },
    {
      HostelsId: 31,
      HostelsName: 'מלון אשכולות נתניה',
      RegionId: 5,
      Address: 'קריית צאנז, נתניה',
      Description: 'מלון נופש משפחתי קרוב לים, בית כנסת וארוחות מהדרין בשפע.',
      NumberOfPlaces: 95,
      kashrutId: 10,
      Phone: '09-8614433',
    },
    {
      HostelsId: 32,
      HostelsName: 'דירות הנופש רמת הגולן',
      RegionId: 2,
      Address: 'קצרין',
      Description:
        'דירות אירוח מרווחות למטיילים בצפון, קרוב למרכזי קניות כשרים.',
      NumberOfPlaces: 35,
      kashrutId: 6,
      Phone: '04-6962211',
    },
    {
      HostelsId: 33,
      HostelsName: 'בית הארחה עין צורים',
      RegionId: 6,
      Address: 'קיבוץ עין צורים',
      Description:
        'אירוח כפרי פסטורלי בשפלת יהודה, מתאים לשבתות גיבוש וסמינרים.',
      NumberOfPlaces: 220,
      kashrutId: 5,
      Phone: '08-8588333',
    },
    {
      HostelsId: 34,
      HostelsName: 'מלון פאר רמדה ירושלים',
      RegionId: 7,
      Address: 'שדרות הרצל, ירושלים',
      Description:
        'מלון מפואר המציע קומות מהדרין מיוחדות, אולמות שמחה ובריכה נפרדת.',
      NumberOfPlaces: 400,
      kashrutId: 3,
      Phone: '02-6599999',
    },
    {
      HostelsId: 35,
      HostelsName: 'אחוזת נווה גליל',
      RegionId: 1,
      Address: 'יישוב תפרח',
      Description: 'מתחם דירות וחדרים מותאם לקהל תורני, אווירה רגועה ומזמינה.',
      NumberOfPlaces: 50,
      kashrutId: 1,
      Phone: '08-9921133',
    },
    {
      HostelsId: 36,
      HostelsName: 'מלון בוטיק רוטשילד בני ברק',
      RegionId: 5,
      Address: 'רחוב רוטשילד, בני ברק',
      Description: 'מלון בוטיק שקט המיועד לאנשי עסקים ומבקרים שומרי מצוות.',
      NumberOfPlaces: 24,
      kashrutId: 2,
      Phone: '03-6164455',
    },
    {
      HostelsId: 37,
      HostelsName: 'פנינת עין כרם',
      RegionId: 7,
      Address: 'עין כרם, ירושלים',
      Description: 'מתחם צימרים ציוריים ומבודדים באווירה כפרית בלב ירושלים.',
      NumberOfPlaces: 14,
      kashrutId: 3,
      Phone: '02-6412233',
    },
    {
      HostelsId: 38,
      HostelsName: 'קמפוס ישיבת נתיבות יוסף',
      RegionId: 6,
      Address: 'מצפה יריחו',
      Description:
        'מתחם חדרים רחב הצופה לנוף מדבר יהודה, מתאים לשבתות קבוצתיות.',
      NumberOfPlaces: 170,
      kashrutId: 1,
      Phone: '02-9944455',
    },
    {
      HostelsId: 39,
      HostelsName: 'צימר המעיין בכפר חסידים',
      RegionId: 4,
      Address: 'כפר חסידים',
      Description: 'נופש כפרי שקט ברמת מנשה, קרוב לקהילה הדתית המקומית.',
      NumberOfPlaces: 18,
      kashrutId: 7,
      Phone: '04-9844411',
    },
    {
      HostelsId: 40,
      HostelsName: 'מלון המלך שלמה טבריה',
      RegionId: 2,
      Address: 'השילוח, טבריה',
      Description:
        'מלון ותיק ומוכר עם נוף פנורמי לכנרת, התאמה מלאה לציבור החרדי.',
      NumberOfPlaces: 130,
      kashrutId: 1,
      Phone: '04-6799911',
    },
    {
      HostelsId: 41,
      HostelsName: 'סוויטות יוקרה בבר יוחאי',
      RegionId: 1,
      Address: 'יישוב בר יוחאי',
      Description: 'מתחם אירוח אקסקלוסיבי למשפחות עם חצר ענקית ופרטיות מוחלטת.',
      NumberOfPlaces: 32,
      kashrutId: 5,
      Phone: '04-6982266',
    },
    {
      HostelsId: 42,
      HostelsName: 'אכסניית הר חברון',
      RegionId: 6,
      Address: 'קריית ארבע',
      Description:
        'מתחם חדרים נקיים קרוב למערת המכפלה, מתאים למשפחות ומטיילים.',
      NumberOfPlaces: 80,
      kashrutId: 3,
      Phone: '02-9961144',
    },
    {
      HostelsId: 43,
      HostelsName: 'מלון לב ירושלים',
      RegionId: 7,
      Address: "המלך ג'ורג' 18, ירושלים",
      Description: 'מלון סוויטות במרכז העיר, מטבחון מאובזר בכל חדר ושירות חם.',
      NumberOfPlaces: 100,
      kashrutId: 3,
      Phone: '02-6213333',
    },
    {
      HostelsId: 44,
      HostelsName: 'מתחם האירוח שדות מיכה',
      RegionId: 6,
      Address: 'מושב שדות מיכה',
      Description:
        'וילות נופש גדולות בשפלת יהודה עם מרחבים ירוקים ומתקני משחקים.',
      NumberOfPlaces: 40,
      kashrutId: 7,
      Phone: '08-9912255',
    },
    {
      HostelsId: 45,
      HostelsName: 'צימרים קול תורה',
      RegionId: 1,
      Address: 'רחוב האר"י, צפת',
      Description: 'חדרי אירוח באווירה צפתית עתיקה ומיוחדת, בלב סמטאות העיר.',
      NumberOfPlaces: 12,
      kashrutId: 1,
      Phone: '04-6924455',
    },
    {
      HostelsId: 46,
      HostelsName: 'מלון פלאזה אשדוד מהדרין',
      RegionId: 5,
      Address: 'שדרות משה דיין, אשדוד',
      Description:
        'מלון חופים חדיש, קרוב לחוף הנפרד, מציע קומות אירוח לשומרי מצוות.',
      NumberOfPlaces: 140,
      kashrutId: 3,
      Phone: '08-8511122',
    },
    {
      HostelsId: 47,
      HostelsName: 'בית הארחה אלון מורה',
      RegionId: 6,
      Address: 'יישוב אלון מורה',
      Description:
        'אירוח קבוצתי חווייתי המשקיף לנופי התנ"ך, כולל סיורים באזור.',
      NumberOfPlaces: 110,
      kashrutId: 7,
      Phone: '02-9406677',
    },
    {
      HostelsId: 48,
      HostelsName: 'אחוזת נופש דרומית',
      RegionId: 9,
      Address: 'נתיבות',
      Description:
        'מתחם דירות אירוח מפוארות וחדשות המתאימות לשבתות חתן משפחתיות.',
      NumberOfPlaces: 55,
      kashrutId: 1,
      Phone: '08-9945566',
    },
    {
      HostelsId: 49,
      HostelsName: 'מלון פרימה פאלאס ירושלים',
      RegionId: 7,
      Address: 'פינס 2, ירושלים',
      Description:
        'מלון המעניק חוויית אירוח יהודית אותנטית, קרוב לשכונות גאולה ומאה שערים.',
      NumberOfPlaces: 120,
      kashrutId: 1,
      Phone: '02-5311111',
    },
    {
      HostelsId: 50,
      HostelsName: 'קמפוס גבעת וושינגטון',
      RegionId: 5,
      Address: 'גבעת וושינגטון',
      Description:
        'מתחם חדרים ענק, אולמות אירועים, מדשאות ומתקני נופש לקבוצות גדולות.',
      NumberOfPlaces: 350,
      kashrutId: 5,
      Phone: '08-8511811',
    },
  ];

  GetHostels() {
    return this.mock_Hostels;
  }

  UpdateHostel(hostel: Int_Hostels) {
    var findHostel = this.mock_Hostels.find(
      (h) => h.HostelsId == hostel.HostelsId,
    );
    if (findHostel) {
      findHostel.Address = hostel.Address;
      findHostel.Description = hostel.Description;
      findHostel.HostelsName = hostel.HostelsName;
      findHostel.NumberOfPlaces = hostel.NumberOfPlaces;
      findHostel.Phone = hostel.Phone;
      findHostel.RegionId = hostel.RegionId;
      findHostel.kashrutId = hostel.kashrutId;
    
    }
  }
}
